name: Déploiement sur Railway

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configuration de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Installation des dépendances
        run: npm ci

      - name: Tests (optionnel)
        run: npm test

      - name: Build de l'image Docker
        run: docker build -t bot-war .

      - name: Déploiement sur Railway
        uses: railway/deploy@v1
        with:
          service: bot-war
          token: ${{ secrets.RAILWAY_TOKEN }}
