name: Deploy to Railway

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - uses: actions/checkout@v3
      - name: Installation des dépendances
        run: npm install

      - uses: actions/checkout@v3
      - name: Lancement des tests
        run: npm test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - run: railway up --service=${{ secrets.RAILWAY_SERVICE_ID }}
